---
# Crear estructura de directorios
- name: Crear estructura de directorios
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /tmp/2do_parcial/alumno
    - /tmp/2do_parcial/equipo

# Generar archivos usando los templates
- name: Generar datos del alumno
  template:
    src: datos_alumno.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

# Generar datos del equipo
- name: Generar datos del equipo
  template:
    src: datos_equipo.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt

# Configurar sudoers
- name: "add NOPASSWD in sudores for group 2PSupervisores"
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%2PSupervisores'
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
